# Generated by Django 3.0.8 on 2020-07-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neolist', '0005_auto_20200716_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neo',
            name='max_diameter',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='neo',
            name='min_diameter',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
    ]
