# Generated by Django 3.0.8 on 2020-07-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neolist', '0007_auto_20200716_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='neo',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
